version: '3.9'

services:
  node_app:
    container_name: node_app
    build: .
    image: walosha/wizardworld-api
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    depends_on:
      - node_db

  node_db:
    container_name: mongo
    image: 'bitnami/mongodb:latest'
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - ./.env
    volumes:
      - node_db_data:/data/db

volumes:
  node_db_data: {}
